mainConfiguration: https://github.com/mattermost/mattermost-gitpod-config

ports:
  - port: 8068
    onOpen: open-browser

# to run detached or not? probably not if want to monitor the stdout
# if set it to $(gp url 8068) like that, it's gonna be a https://
# and gonna act like https. is gp and url two separate variables?

# what's shm-size?

tasks:
  - name: Gitlab
    command: |
      docker run --hostname $(gp url 8068) \
        --publish 8070:443 --publish 8068:80 --publish 8072:22 \
        --name gitlab \
        --volume $GITLAB_HOME/config:/etc/gitlab \
        --volume $GITLAB_HOME/logs:/var/log/gitlab \
        --volume $GITLAB_HOME/data:/var/opt/gitlab \
        --shm-size 256m \
        gitlab/gitlab-ee:latest
    env:
      GITLAB_HOME: /srv/gitlab

github:
  prebuilds:
    master: true
    pullRequests: true

vscode:
  extensions:
    - golang.go

workspaceLocation:
  mattermost-plugin-gitlab/mattermost.code-workspace

# additionalRepositories:
#   - url: https://github.com/mattermost/mattermost-server
#   - url: https://github.com/mattermost/mattermost-webapp

#   - name: Webapp
#     before: |
#       cd ../mattermost-webapp
#       export MM_SERVICESETTINGS_SITEURL=$(gp url 8065)
#     init: |
#       mkdir dist
#       cd ../mattermost-server
#       ln -nfs ../mattermost-webapp/dist client
#       cd ../mattermost-webapp

#       nvm install v16.4.0
#       nvm alias default v16.4.0
#       npm i
#       make build
#     command: |
#       nvm use v16.4.0
#       npm i
#       make run
#     openMode: split-right

#   - name: Plugin
#     init: |
#       source /workspace/mattermost-gitpod-config/scripts/plugin/init-plugin-project.sh
#     command: |
#       gp await-port 8065
#       echo "Server is running at $(gp url 8065)"
#       source /workspace/mattermost-gitpod-config/scripts/plugin/run-plugin-project.sh
#     env:
#       MM_SERVICESETTINGS_ENABLEDEVELOPER: true

#   - name: App
#     init: |
#       source /workspace/mattermost-gitpod-config/scripts/app/init-app-project.sh
#     command: |
#       source /workspace/mattermost-gitpod-config/scripts/app/run-app-project.sh
